id: PB5369054
initial_creation_type: input
source_metadata:
  title: Nyala Pema Dündul Series
  language: es
  description: 'Texts by and about the great siddha of Nyarong, Nyala Pema Dündul
    (nyag bla padma bdud ''dul, 1816–1872):'
  volume:
    a25837179c14410dbc568c508e8fd7b2:
      title: Advice Revealing How Our Faults Become Clear
      parent: Advice
    0a4436ab900d40bab731bf0d6fb643ab:
      title: Advice on Abandoning the Eight Worldly Concerns
      parent: Advice
    7ac6bc12a1e94bb4b1351d9b8068c99b:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    b704f32e094142b2bd4af1c6a91c7220:
      title: Signs that the Common Preliminary Practices Have Penetrated the Mind
      parent: Advice
    95d803e02e49487980997096bcd85c3d:
      title: Song of Advice for Giving Up Meat Eating
      parent: Advice
    e4c133b284c34bd7912c56a17f6003eb:
      title: The Heaven of Solitude
      parent: Advice
    0d0c5ef0ae074005a5489fcf38f2236a:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Confession
    af7770df65914b07ae852087329cb340:
      title: Dharmakāya Transference
      parent: Phowa
    398e7e09c3104d559bfcff89e5dea581:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
created_at: '2022-03-01T01:03:40.616376'
last_modified_at: '2022-03-01T01:03:40.616379'
